# Generated by Django 3.2.9 on 2022-01-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='length',
            field=models.IntegerField(default=0, verbose_name='length [sec]'),
        ),
    ]
