# Generated by Django 3.2.9 on 2022-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_music_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='bpm',
            field=models.FloatField(verbose_name='bpm'),
        ),
        migrations.AlterField(
            model_name='music',
            name='length',
            field=models.FloatField(default=0.0, verbose_name='length [sec]'),
        ),
    ]
