# Generated by Django 3.2.9 on 2021-12-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='occurred at')),
                ('location_map_image_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='location map image url')),
                ('location_map_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='location map url')),
                ('trigger_type', models.IntegerField(choices=[(0, 'entered'), (1, 'exited')], verbose_name='trigger type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Gps',
                'verbose_name_plural': 'Gps',
            },
        ),
    ]
