name: Docker

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  nginx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Login to ghcr.io registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build and Push"
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            ghcr.io/itk13201/smart-watch-iot-server_nginx:${{ github.sha }}
            ghcr.io/itk13201/smart-watch-iot-server_nginx:latest
          file: ./docker/nginx/Dockerfile

  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Login to ghcr.io registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build and Push"
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            ghcr.io/itk13201/smart-watch-iot-server_backend:${{ github.sha }}
            ghcr.io/itk13201/smart-watch-iot-server_backend:latest
          file: ./docker/backend/Dockerfile
          target: production
