name: Docker

on:
  push:
    tags:
      - 'v*'

jobs:
  nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/itk13201/smart-watch-iot-server_nginx
      - name: "Login to ghcr.io registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build and Push"
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./docker/nginx/Dockerfile

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/itk13201/smart-watch-iot-server_backend
      - name: "Login to ghcr.io registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build and Push"
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./docker/backend/Dockerfile
          target: production
