name: Docker

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  nginx:
    runs-on: ubuntu-latest

    steps:
      - name: "Build: checkout"
        uses: actions/checkout@v2
      - name: "Build: docker image"
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_sha: true
          tags: ghcr.io/${{ github.repository_owner }}/smart-watch-iot-server:latest
          dockerfile: ./docker/nginx/Dockerfile

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: "Build: checkout"
        uses: actions/checkout@v2
      - name: "Build: docker image"
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_sha: true
          tags: latest
          dockerfile: ./docker/backend/Dockerfile